version: '3.8'

services:
  postgres:
    image: postgres
    container_name: cinema-booking-db
    restart: always
    environment:
      POSTGRES_DB: cinema_booking
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password

      POSTGRES_INITDB_ARGS: "--data-checksums"

    ports:
      - "5435:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres.init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
    driver: local